Make Lever Posting auto routes unique
EtchUK/Etch.OrchardCore.Lever pull request #3
Opened 2020-12-14 13:18 UTC by mobinzk

- Make Lever Posting auto routes unique  - Closes #1
- Remove references to `NewsPost` - Closes #2

2020-12-16 16:29 UTC, JoeBerkley requested changes

2020-12-16 16:29 UTC, JoeBerkley commented on Services/LeverPostingService.cs
> +            while (true == true)
You could tidy up this while by instead using `!IsUniqueURL(contentItemUrl)` as what you pass into the parameter for the loop

2020-12-17 11:46 UTC, peterkeating commented on Services/LeverPostingService.cs
> +            while (true == true)
Lever has picked up line `190` as a bug as the `==` is irrelevant, `while (true)` is all that's needed.

2020-12-22 11:01 UTC, peterkeating commented on Services/LeverPostingService.cs
> +            while (true == true)
Resolved by removing this function all together.

2020-12-22 11:35 UTC, merged